"""
Stage F — Ligand preparation and docking.

Pipeline for each ligand:
  1. smiles_to_3d()     — SMILES → 3-D SDF/MOL2 via RDKit (ETKDG conformer)
  2. dock_gnina()       — AutoDock-GPU/GNINA docking → best pose SDF
  3. parameterize_ligand() — GAFF2 parameters via ACPYPE or OpenFF SMIRNOFF
  4. prepare_ligands()  — high-level: runs all three steps for a list of LigandContext dicts

Usage
-----
from orchestrator.ligands import prepare_ligands

ligand_files = prepare_ligands(ligand_contexts, protein_pdb_string, tmpdir)
# Returns list of {"name": ..., "mol2": ..., "frcmod": ..., "itp": ...}
"""

import logging
import os
import shutil
import subprocess
import tempfile
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Step 1: SMILES → 3-D structure (RDKit ETKDG)
# ---------------------------------------------------------------------------


def smiles_to_3d(smiles: str, ligand_name: str, out_dir: str) -> str:
    """
    Convert a SMILES string to a 3-D SDF file using RDKit ETKDG conformer generation.

    Parameters
    ----------
    smiles : str
        SMILES string of the ligand.
    ligand_name : str
        Used to name the output file: <ligand_name>.sdf
    out_dir : str
        Directory to write the SDF file.

    Returns
    -------
    str
        Absolute path to the generated SDF file.

    Raises
    ------
    RuntimeError
        If RDKit is not installed or conformer generation fails.
    """
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem
    except ImportError:
        raise RuntimeError(
            "RDKit is not installed. "
            "Install: conda install -c conda-forge rdkit"
        )

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"RDKit could not parse SMILES: {smiles!r}")

    mol = Chem.AddHs(mol)

    # ETKDG: distance-geometry conformer with knowledge-based torsion library
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)
    if result == -1:
        raise RuntimeError(
            f"RDKit ETKDG conformer generation failed for {ligand_name!r} "
            f"(SMILES: {smiles!r}). "
            "Check that the SMILES is valid and the molecule is not too large."
        )

    AllChem.MMFFOptimizeMolecule(mol)

    sdf_path = os.path.join(out_dir, f"{ligand_name}.sdf")
    writer = Chem.SDWriter(sdf_path)
    writer.write(mol)
    writer.close()

    logger.info(f"RDKit: 3-D conformer written to {sdf_path}")
    return sdf_path


# ---------------------------------------------------------------------------
# Step 2: Docking via GNINA
# ---------------------------------------------------------------------------


def dock_gnina(
    ligand_sdf: str,
    protein_pdb: str,
    binding_site: Optional[List[int]],
    out_dir: str,
    gnina_bin: str = "gnina",
    exhaustiveness: int = 8,
) -> str:
    """
    Dock a ligand to a protein using GNINA (AutoDock-GPU-compatible docking).

    If binding_site residue numbers are provided, the docking box is centred on
    the CA centroid of those residues with a 20 Å edge length.
    If binding_site is absent, a global blind docking box is used.

    Parameters
    ----------
    ligand_sdf : str
        Path to the 3-D ligand SDF generated by smiles_to_3d().
    protein_pdb : str
        Path to the receptor PDB file.
    binding_site : list of int or None
        Residue numbers defining the binding pocket (CA centroid → box centre).
    out_dir : str
        Directory for output files.
    gnina_bin : str
        Name or path of the GNINA binary (default: "gnina").
    exhaustiveness : int
        GNINA exhaustiveness parameter (higher = more sampling, slower).

    Returns
    -------
    str
        Path to the best-pose SDF output from GNINA.

    Raises
    ------
    RuntimeError
        If GNINA binary is not found or docking fails.
    """
    gnina = shutil.which(gnina_bin)
    if gnina is None:
        raise RuntimeError(
            f"GNINA binary '{gnina_bin}' not found. "
            "Download from https://github.com/gnina/gnina/releases "
            "and set GNINA_BIN in .env, or place gnina on PATH."
        )

    docked_sdf = os.path.join(out_dir, "docked.sdf")

    if binding_site and len(binding_site) >= 1:
        # Compute CA centroid from the binding site residues
        center_x, center_y, center_z = _ca_centroid(protein_pdb, binding_site)
        box_size = 20.0  # Å
        logger.info(
            f"GNINA: docking to binding site residues {binding_site}. "
            f"Box centre ({center_x:.2f}, {center_y:.2f}, {center_z:.2f}) Å, "
            f"edge {box_size} Å"
        )
        cmd = [
            gnina,
            "-r", protein_pdb,
            "-l", ligand_sdf,
            "-o", docked_sdf,
            "--center_x", str(center_x),
            "--center_y", str(center_y),
            "--center_z", str(center_z),
            "--size_x", str(box_size),
            "--size_y", str(box_size),
            "--size_z", str(box_size),
            "--exhaustiveness", str(exhaustiveness),
            "--num_modes", "1",
            "--quiet",
        ]
    else:
        # Blind docking: auto-detect the full protein extent
        logger.info("GNINA: blind docking (no binding site specified)")
        cmd = [
            gnina,
            "-r", protein_pdb,
            "-l", ligand_sdf,
            "-o", docked_sdf,
            "--autobox_ligand", protein_pdb,
            "--exhaustiveness", str(exhaustiveness),
            "--num_modes", "1",
            "--quiet",
        ]

    logger.debug(f"GNINA command: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=out_dir)
    if result.returncode != 0:
        raise RuntimeError(
            f"GNINA docking failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout[-800:]}\n"
            f"stderr: {result.stderr[-800:]}"
        )

    if not os.path.isfile(docked_sdf):
        raise RuntimeError(f"GNINA completed but docked.sdf not found in {out_dir}")

    logger.info(f"GNINA: best pose written to {docked_sdf}")
    return docked_sdf


def dock_vina(
    ligand_sdf: str,
    protein_pdb: str,
    binding_site: Optional[List[int]],
    out_dir: str,
    exhaustiveness: int = 8,
) -> str:
    """
    Dock a ligand using AutoDock-Vina (Python bindings).

    Fallback for when the GNINA binary is unavailable (e.g. ARM64 dev machines).
    Produces a docked SDF at <out_dir>/docked_vina.sdf.

    Requires: pip install vina
    """
    try:
        from vina import Vina
    except ImportError:
        raise RuntimeError(
            "vina is not installed. Install: pip install vina"
        )
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem
    except ImportError:
        raise RuntimeError("RDKit is required for Vina docking SDF conversion.")

    # Vina requires PDBQT format; convert via RDKit + meeko if available,
    # otherwise use a simple charge-stripping conversion.
    try:
        import meeko
        _meeko_available = True
    except ImportError:
        _meeko_available = False

    receptor_pdbqt = os.path.join(out_dir, "receptor.pdbqt")
    ligand_pdbqt   = os.path.join(out_dir, "ligand.pdbqt")
    docked_pdbqt   = os.path.join(out_dir, "docked_vina.pdbqt")
    docked_sdf     = os.path.join(out_dir, "docked_vina.sdf")

    # --- Convert receptor PDB → PDBQT (strip H, add charges with mk_prepare_receptor or fallback) ---
    if _meeko_available:
        import meeko
        mk = meeko.MoleculePreparation()
        # meeko receptor preparation
        subprocess.run(
            ["mk_prepare_receptor.py", "-i", protein_pdb, "-o", receptor_pdbqt],
            capture_output=True, check=False,
        )
    if not os.path.isfile(receptor_pdbqt):
        # Minimal fallback: rename PDB to PDBQT (Vina tolerates plain PDB as receptor)
        import shutil as _shutil
        _shutil.copy(protein_pdb, receptor_pdbqt)

    # --- Convert ligand SDF → PDBQT ---
    mol = Chem.MolFromMolFile(ligand_sdf, removeHs=False)
    if mol is None:
        raise RuntimeError(f"RDKit could not load ligand SDF: {ligand_sdf}")

    if _meeko_available:
        mk = meeko.MoleculePreparation()
        mk.prepare(mol)
        mk.write_pdbqt_file(ligand_pdbqt)
    else:
        # Fallback: write SDF with explicit H, rename to pdbqt (Vina can often read it)
        Chem.MolToMolFile(mol, ligand_pdbqt)

    # --- Compute docking box ---
    if binding_site and len(binding_site) >= 1:
        cx, cy, cz = _ca_centroid(protein_pdb, binding_site)
        box_size = 20.0
    else:
        coords = _all_ca_coords(protein_pdb)
        if coords:
            n = len(coords)
            cx = sum(c[0] for c in coords) / n
            cy = sum(c[1] for c in coords) / n
            cz = sum(c[2] for c in coords) / n
        else:
            cx = cy = cz = 0.0
        box_size = 30.0  # larger box for blind docking

    logger.info(
        f"Vina: docking box centre ({cx:.2f}, {cy:.2f}, {cz:.2f}) Å, "
        f"edge {box_size:.0f} Å, exhaustiveness={exhaustiveness}"
    )

    v = Vina(sf_name="vina", verbosity=0)
    v.set_receptor(receptor_pdbqt)
    v.set_ligand_from_file(ligand_pdbqt)
    v.compute_vina_maps(
        center=[cx, cy, cz],
        box_size=[box_size, box_size, box_size],
    )
    v.dock(exhaustiveness=exhaustiveness, n_poses=1)
    v.write_poses(docked_pdbqt, n_poses=1, overwrite=True)

    # --- Convert best pose PDBQT → SDF ---
    if _meeko_available:
        pdbqt_mol = meeko.PDBQTMolecule.from_file(docked_pdbqt, skip_typing=True)
        rdkit_mol = meeko.RDKitMolCreate.from_pdbqt_mol(pdbqt_mol)[0]
        if rdkit_mol is not None:
            writer = Chem.SDWriter(docked_sdf)
            writer.write(rdkit_mol)
            writer.close()
    if not os.path.isfile(docked_sdf):
        # Last resort: copy pdbqt as sdf (OpenFF can sometimes parse it)
        import shutil as _shutil
        _shutil.copy(docked_pdbqt, docked_sdf)

    logger.info(f"Vina: best pose written to {docked_sdf}")
    return docked_sdf


def _ca_centroid(protein_pdb: str, residue_numbers: List[int]) -> tuple:
    """
    Compute the XYZ centroid of CA atoms for the given residue numbers.
    Falls back to the full-protein CA centroid if no matching residues are found.
    """
    coords = []
    res_set = set(residue_numbers)
    try:
        with open(protein_pdb) as fh:
            for line in fh:
                if not line.startswith("ATOM"):
                    continue
                if line[12:16].strip() != "CA":
                    continue
                try:
                    res_num = int(line[22:26].strip())
                except ValueError:
                    continue
                if res_num in res_set:
                    try:
                        x = float(line[30:38])
                        y = float(line[38:46])
                        z = float(line[46:54])
                        coords.append((x, y, z))
                    except ValueError:
                        pass
    except OSError:
        pass

    if not coords:
        # Fallback: full-protein CA centroid
        coords = _all_ca_coords(protein_pdb)

    if not coords:
        return 0.0, 0.0, 0.0

    n = len(coords)
    cx = sum(c[0] for c in coords) / n
    cy = sum(c[1] for c in coords) / n
    cz = sum(c[2] for c in coords) / n
    return cx, cy, cz


def _all_ca_coords(protein_pdb: str) -> list:
    coords = []
    try:
        with open(protein_pdb) as fh:
            for line in fh:
                if not line.startswith("ATOM"):
                    continue
                if line[12:16].strip() != "CA":
                    continue
                try:
                    coords.append((float(line[30:38]), float(line[38:46]), float(line[46:54])))
                except ValueError:
                    pass
    except OSError:
        pass
    return coords


# ---------------------------------------------------------------------------
# Step 3: Ligand parameterization (ACPYPE → GAFF2 or OpenFF SMIRNOFF)
# ---------------------------------------------------------------------------


def parameterize_ligand_acpype(
    docked_sdf: str,
    ligand_name: str,
    out_dir: str,
) -> Dict[str, str]:
    """
    Generate GAFF2 force-field parameters for a docked ligand using ACPYPE.

    ACPYPE calls AmberTools antechamber internally and produces:
      - <ligand_name>.itp   — GROMACS include topology
      - <ligand_name>.gro   — GROMACS coordinate file for the ligand
      - <ligand_name>.mol2  — MOL2 for inspection

    Parameters
    ----------
    docked_sdf : str
        Path to the docked pose SDF (best pose from dock_gnina).
    ligand_name : str
        Name for the ligand residue in the topology.
    out_dir : str
        Directory for output files.

    Returns
    -------
    dict with keys: "itp", "gro", "mol2"

    Raises
    ------
    RuntimeError
        If acpype is not installed or parameterization fails.
    """
    acpype = shutil.which("acpype")
    if acpype is None:
        raise RuntimeError(
            "acpype is not installed. "
            "Install: pip install acpype\n"
            "Also requires AmberTools: conda install -c conda-forge ambertools"
        )

    logger.info(f"ACPYPE: generating GAFF2 parameters for {ligand_name}...")
    result = subprocess.run(
        [acpype, "-i", docked_sdf, "-n", "0", "-b", ligand_name, "-f", "gmx"],
        capture_output=True,
        text=True,
        cwd=out_dir,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"ACPYPE failed for {ligand_name} (exit {result.returncode}):\n"
            f"stdout: {result.stdout[-800:]}\n"
            f"stderr: {result.stderr[-800:]}"
        )

    # ACPYPE writes into <ligand_name>.acpype/
    acpype_dir = os.path.join(out_dir, f"{ligand_name}.acpype")
    paths: Dict[str, str] = {}
    for ext, key in [
        (f"{ligand_name}_GMX.itp", "itp"),
        (f"{ligand_name}_GMX.gro", "gro"),
        (f"{ligand_name}.mol2",   "mol2"),
    ]:
        candidate = os.path.join(acpype_dir, ext)
        if os.path.isfile(candidate):
            paths[key] = candidate
        else:
            logger.warning(f"ACPYPE: expected output not found: {candidate}")

    logger.info(f"ACPYPE: parameterization complete for {ligand_name}: {list(paths.keys())}")
    return paths


def parameterize_ligand_openff(
    docked_sdf: str,
    ligand_name: str,
    out_dir: str,
) -> Dict[str, str]:
    """
    Generate SMIRNOFF (OpenFF 2.x) force-field parameters for a docked ligand.

    Returns an OpenMM-compatible XML file (<ligand_name>_openff.xml).

    Requires:
        pip install openff-toolkit openff-forcefields

    Parameters
    ----------
    docked_sdf : str
        Path to the docked pose SDF.
    ligand_name : str
        Name for the output file prefix.
    out_dir : str
        Directory for output files.

    Returns
    -------
    dict with key "xml" → path to the serialized OpenMM XML system.

    Raises
    ------
    RuntimeError
        If openff-toolkit is not installed or parameterization fails.
    """
    try:
        from openff.toolkit import Molecule, ForceField as OpenFFForceField
        from openff.toolkit.utils.exceptions import RadicalsNotSupportedError
    except ImportError:
        raise RuntimeError(
            "openff-toolkit is not installed. "
            "Install: pip install openff-toolkit openff-forcefields"
        )

    try:
        from openff.interchange import Interchange
    except ImportError:
        raise RuntimeError(
            "openff-interchange is not installed. "
            "Install: pip install openff-interchange"
        )

    logger.info(f"OpenFF: parameterizing {ligand_name} with SMIRNOFF sage-2.1.0...")

    try:
        mol = Molecule.from_file(docked_sdf, file_format="sdf")
    except Exception as e:
        raise RuntimeError(f"OpenFF could not load SDF for {ligand_name}: {e}")

    try:
        ff = OpenFFForceField("openff-2.1.0.offxml")
        interchange = Interchange.from_smirnoff(force_field=ff, topology=mol.to_topology())
    except RadicalsNotSupportedError:
        raise RuntimeError(
            f"OpenFF does not support radicals in {ligand_name}. "
            "Use ACPYPE (GAFF2) for this ligand instead."
        )
    except Exception as e:
        raise RuntimeError(f"OpenFF parameterization failed for {ligand_name}: {e}")

    xml_path = os.path.join(out_dir, f"{ligand_name}_openff.xml")
    interchange.to_openmm_system()  # validates the system
    with open(xml_path, "w") as fh:
        import openmm
        fh.write(openmm.XmlSerializer.serialize(interchange.to_openmm_system()))

    logger.info(f"OpenFF: XML system written to {xml_path}")
    return {"xml": xml_path}


# ---------------------------------------------------------------------------
# High-level entry point
# ---------------------------------------------------------------------------


def prepare_ligands(
    ligand_contexts: List[Dict[str, Any]],
    protein_pdb_string: str,
    tmpdir: str,
    gnina_bin: str = "gnina",
    use_openff: bool = False,
) -> List[Dict[str, Any]]:
    """
    Full ligand preparation pipeline for a list of LigandContext dicts.

    For each ligand that has a SMILES string:
      1. Generate a 3-D conformer (RDKit ETKDG)
      2. Dock to the protein (GNINA)
      3. Parameterize (ACPYPE GAFF2 by default; OpenFF SMIRNOFF if use_openff=True)

    Ligands without SMILES are skipped (warning logged).

    Parameters
    ----------
    ligand_contexts : list of dict
        Each dict should have {"name": str, "smiles": str, "binding_site": list[int] | None}.
    protein_pdb_string : str
        Protein structure in PDB format (used as docking receptor).
    tmpdir : str
        Working directory for all intermediate files.
    gnina_bin : str
        Path/name of the GNINA binary.
    use_openff : bool
        If True, use OpenFF SMIRNOFF instead of ACPYPE GAFF2.

    Returns
    -------
    list of dict
        One dict per successfully prepared ligand:
        {
            "name": str,
            "docked_sdf": str,          # path to best-pose SDF
            "itp":  str | None,         # GROMACS topology include (ACPYPE)
            "gro":  str | None,         # GROMACS coordinate file (ACPYPE)
            "mol2": str | None,         # MOL2 file (ACPYPE)
            "xml":  str | None,         # OpenMM XML (OpenFF)
            "parameterizer": str,       # "acpype" | "openff" | "none"
        }
    """
    protein_pdb_path = os.path.join(tmpdir, "receptor.pdb")
    with open(protein_pdb_path, "w") as fh:
        fh.write(protein_pdb_string)

    results: List[Dict[str, Any]] = []

    for lig in ligand_contexts:
        name = lig.get("name", "LIG")
        smiles = lig.get("smiles")
        binding_site = lig.get("binding_site")

        if not smiles:
            logger.warning(f"Ligand '{name}' has no SMILES — skipping parameterization")
            continue

        lig_dir = os.path.join(tmpdir, f"lig_{name}")
        os.makedirs(lig_dir, exist_ok=True)

        entry: Dict[str, Any] = {
            "name": name,
            "docked_sdf": None,
            "itp": None,
            "gro": None,
            "mol2": None,
            "xml": None,
            "parameterizer": "none",
        }

        # Step 1: SMILES → 3-D SDF
        try:
            sdf_path = smiles_to_3d(smiles, name, lig_dir)
        except Exception as e:
            logger.error(f"Ligand '{name}': 3-D conformer failed: {e}")
            continue

        # Step 2: Dock — try GNINA first, fall back to Vina, then undocked conformer
        try:
            docked_sdf = dock_gnina(
                sdf_path, protein_pdb_path, binding_site, lig_dir, gnina_bin=gnina_bin
            )
            entry["docked_sdf"] = docked_sdf
        except RuntimeError as gnina_err:
            logger.warning(f"Ligand '{name}': GNINA unavailable ({gnina_err}). Trying Vina fallback...")
            try:
                docked_sdf = dock_vina(
                    sdf_path, protein_pdb_path, binding_site, lig_dir
                )
                entry["docked_sdf"] = docked_sdf
                logger.info(f"Ligand '{name}': Vina docking succeeded.")
            except RuntimeError as vina_err:
                logger.warning(
                    f"Ligand '{name}': Vina docking also failed ({vina_err}). "
                    "Using undocked conformer."
                )
                entry["docked_sdf"] = sdf_path  # fall back to undocked pose

        # Step 3: Parameterize
        source_sdf = entry["docked_sdf"] or sdf_path
        try:
            if use_openff:
                params = parameterize_ligand_openff(source_sdf, name, lig_dir)
                entry["xml"] = params.get("xml")
                entry["parameterizer"] = "openff"
            else:
                params = parameterize_ligand_acpype(source_sdf, name, lig_dir)
                entry["itp"]  = params.get("itp")
                entry["gro"]  = params.get("gro")
                entry["mol2"] = params.get("mol2")
                entry["parameterizer"] = "acpype"
        except RuntimeError as e:
            logger.warning(f"Ligand '{name}': parameterization failed: {e}")
            entry["parameterizer"] = "none"

        results.append(entry)
        logger.info(
            f"Ligand '{name}' prepared: parameterizer={entry['parameterizer']}, "
            f"docked_sdf={entry['docked_sdf']}"
        )

    return results
